# Generated by Django 5.1 on 2025-11-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
    ]
